#!/bin/bash
sudo apt update
sudo apt-get install -y \
     docker-compose \
     unzip

curl -fsSL https://get.docker.com/
git clone https://github.com/yossieadvindo/mutilidae.git
cd mutilidae
wget https://nchc.dl.sourceforge.net/project/mutillidae/mutillidae-project/NOT-LATEST-MUTILLIDAE-MOVED-TO-GITHUB-mutillidae-2.6.67.zip
unzip NOT-LATEST-MUTILLIDAE-MOVED-TO-GITHUB-mutillidae-2.6.67.zip
sudo docker-compose up
